version: '3.7'

services:
  service-a:
    build:
      context: ./ServiceA
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./ServiceA:/appa
    depends_on:
      - service-b
      - zipkin
  service-b:
    build:
      context: ./ServiceB
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ServiceB:/appb
    depends_on:
      - zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"